Project added
JatinRanka/DevTube-Frontend pull request #1
Opened 2021-05-06 17:16 UTC by JatinRanka

2021-05-08 17:02 UTC, Akshay-Laxmipathi commented
Delete playlist button is not functional

2021-05-09 07:28 UTC, Ashishgupta08 requested changes

2021-05-09 07:28 UTC, Ashishgupta08 commented on src/views/VideoPage/index.jsx
> +	return <VideoPageComponent videoDetails={videoDetails} videosList={videosList} />;
Limit similar videos up to 5 or 6

2021-05-09 07:28 UTC, Ashishgupta08 commented on src/components/SaveVideoModal/index.jsx
> +				<button onClick={handleAddPlaylistAndSave}>Save</button>
Restrict the empty playlist name

2021-05-09 07:29 UTC, Ashishgupta08 commented
Remove underline from all the links.
Add more data and create a separate Liked Videos Page.
Check the Play on Hover on Home Page

2021-06-30 05:38 UTC, merged